### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by natehak** [shadowmint/ue4-static-plugin#2]
Plugin is currently unlicensed. This means the project technically cannot be used *anybody* without violating copyright.

**Comment by shadowmint** [comment]
Its MIT license.

**Comment by natehak** [comment]
Want me to send a pull request adding the license file?

**Comment by shadowmint** [comment]
If you're keen, sure. otherwise I'll add it in a hour or so when I get
home.

**Comment by shadowmint** [comment]
sorted~
